### ISSUE TITLE
User interaction with background page

### ISSUE THREAD

**Issue by defjosiah** [defjosiah/dowling-hart#1]
Right now the only view on the /background/ page is the dots on on the page that call a jquery handler that unhides the corresponding section on a click. 

In the final version, there should be an initial box that tells them to explore the timeline. Following this, there should be a link to the /explore/ page that is hidden in the beginning, and appears once they've visited all of the points on the timeline. This could probably be a counter of some sort in the javascript function on the page (background.html)

**Comment by wcaleb** [comment]
Will work on this on the `background-ui` branch.

**Comment by wcaleb** [comment]
Closed with 7ac17a76e5ff0fa3c2f48ec35b9322396903d206.

**Comment by defjosiah** [comment]
This is a really clever way to do it, I'll be adding that in the next section

**Comment by wcaleb** [comment]
[StackOverflow is my friend](http://stackoverflow.com/a/17675863/1848454).
