### ISSUE TITLE
Glossary words hover over or link to definition (timeline intro and documents)

### ISSUE THREAD

**Issue by ClareCat21** [defjosiah/dowling-hart#18]
Just tell me how (if it's something easy enough for me to do).

**Comment by wcaleb** [comment]
I'll work on this and then let you know. It will probably require some modifications to the Markdown files.

**Comment by wcaleb** [comment]
@josiahbgrace Didn't want to close this issue until you had a chance to look at this implementation and see what you think. It's not the prettiest solution, but it has the virtue of keeping the Markdown pretty plain, and also keeps both the full glossary and pop-up at the same time (important if viewer is on a mobile device, for example).

**Comment by defjosiah** [comment]
I think it looks great... I'm finished with meetings now so I'll be working on my portions now, just FYI

Feel free to close it

**Comment by wcaleb** [comment]
@ClareCat21 To get the "pop up" behavior on the other explore documents, you'll have to follow the syntax in [the Davis speech](https://github.com/josiahbgrace/dowling-hart/blob/913720bde8523f639c9af4ef0c0bce9eb2fea888/text/explore/expl_1_mem.txt).

Basically, after each word that you want to define, add a footnote reference: `[^1]`. Then, you should later include the footnote, like this: `[^1]: term and definition`.
