### ISSUE TITLE
Timeline points UI

### ISSUE THREAD

**Issue by defjosiah** [defjosiah/dowling-hart#2]
Move the date below the timeline point in the background.html view, add the grey bars between the points on the timeline programmatically. In the background.html file there is a sorted list of documents by their date and position on the screen, this probably involves drawing a rectangle of varying width by subtracting the next documents position from the previous one for a width. For example (doc1, 1905, 37.5%) and (doc2, 1935, 78.5%), would need a rectangle starting at 40% (or some other buffer amount) and ending at 78% of a constant height. 

![screen shot 2014-07-27 at 2 50 20 pm](https://cloud.githubusercontent.com/assets/3061661/3714954/4914ae90-15c7-11e4-8232-3118edbd6587.png)

**Comment by wcaleb** [comment]
OK, I'm working on this on the `timeline-ui` branch.
