### ISSUE TITLE
glossary mix up

### ISSUE THREAD

**Issue by ClareCat21** [defjosiah/dowling-hart#20]
first several glossary terms for documents after document 1 are taken from document 1 (battle of Thermopylae, esteemed, etc.)

**Comment by wcaleb** [comment]
I think I know why. I will look at this in the morning.

**Comment by ClareCat21** [comment]
The glossary terms for the timeline (in 1861, 1882, and 1968) don't show up either. I put them in the same way as in explore, but I don't know if the footnote feature is activated for background or maybe just for explore.

**Comment by ClareCat21** [comment]
@wcaleb should I go through and do the same thing for the other documents in explore and background, then? Making each term a single word?

**Comment by wcaleb** [comment]
I've already done it for all the explore documents. Are there going to be footnotes in the background texts?

**Comment by ClareCat21** [comment]
Yes they are added - 1861, 1882, and 1968 are the only ones that have them, I think.

**Comment by wcaleb** [comment]
Ok. I'll need to make a change to the script to enable footnotes there, and yes, you'll need to go through and use the new word syntax on the footnotes. Sorry for the additional work, but it was the only way to prevent the problem!

**Comment by ClareCat21** [comment]
Thanks for fixing it - I'll go through and do that right now!

**Comment by ClareCat21** [comment]
footnotes were removed so it'll take a little bit longer than expected

**Comment by ClareCat21** [comment]
stupid question - how do I revert?

**Comment by wcaleb** [comment]
I can revert those commits for you.

**Comment by ClareCat21** [comment]
thanks!
