### ISSUE TITLE
can't select correct multiple choice answer and therefore can't continue since I couldn't complete them

### ISSUE THREAD

**Issue by ClareCat21** [defjosiah/dowling-hart#24]
I can select multiple choice that are incorrect, but it doesn't allow me to select the correct answer

**Comment by wcaleb** [comment]
Are you sure that it's not selecting the correct answer when you click on it?
- Does the color change?
- If the color doesn't change, try going through all the quizzes and clicking on the correct answer anyway; then see if it let's you continue.

Let us know what happens ...

**Comment by nathanandrus778** [comment]
I was able to select the MC question answers, but there was no real interface for it. I wasn't sure if I was clicking on them and getting them right until I managed to click through all of them and got the arrow to continue to the sorting game.

**Comment by wcaleb** [comment]
Did the color of the answer change when you clicked on the correct one?

And did an alert pop up and the hint display if you clicked a wrong one?

**Comment by ClareCat21** [comment]
Ok I did the same thing as Nathan and it worked. The color of the answer did not change - there was no indication I got it right. If I clicked a wrong one, the hint display did pop up

**Comment by wcaleb** [comment]
I've tried to improve the UI with a84a5b8fa204a0b95d67c5cb4f623fc61987809b. Once @josiahbgrace pushes the latest commits to the server, you can try it out.

**Comment by defjosiah** [comment]
@wcaleb it's been pushed, I can't figure out why it wasn't working for them... I'm checking the server logs to see if it might be something else

**Comment by ClareCat21** [comment]
Still isn't working for me

**Comment by defjosiah** [comment]
Can you attach a screenshot of what you are seeing?

**Comment by defjosiah** [comment]
Cause it is showing for me

**Comment by ClareCat21** [comment]
I had selected the correct answer. 
![fullscreen capture 7302014 12113 pm](https://cloud.githubusercontent.com/assets/6454900/3753930/8f7c78ee-1816-11e4-8ca3-d07a3cf04db1.jpg)

**Comment by defjosiah** [comment]
That's interesting... that's a ton of commits behind, there are still numbers instead of letters for the options for the multiple choice

**Comment by defjosiah** [comment]
this is my view

**Comment by defjosiah** [comment]
![screen shot 2014-07-30 at 1 24 38 pm](https://cloud.githubusercontent.com/assets/3061661/3753959/d1153f70-1816-11e4-8c5f-10b57cd2a708.png)

and this
![screen shot 2014-07-30 at 1 25 05 pm](https://cloud.githubusercontent.com/assets/3061661/3753963/dca45646-1816-11e4-8db3-c194b747b9d5.png)

**Comment by ClareCat21** [comment]
oh wow. way different

**Comment by wcaleb** [comment]
@ClareCat21 Have you quit your browser entirely recently? You may also have to clear your browser cache.

**Comment by defjosiah** [comment]
yeah, this is going to sound dumb, but did you make sure to refresh, and close out the page, your cache is probably old

**Comment by ClareCat21** [comment]
I'll try that right now - i've closed tabs but not the entire browser

**Comment by ClareCat21** [comment]
Didn't work after closing the browser, but I cleared my cache and it worked after that. Sorry about that!

**Comment by defjosiah** [comment]
totally fine, that's my bad for not letting you know that that is something to remember
