### ISSUE TITLE
Add {{figure}} and caption syntax to the remaining text/backg_* files

### ISSUE THREAD

**Issue by defjosiah** [defjosiah/dowling-hart#7]

**Comment by defjosiah** [comment]
@ClareCat21 this issue can encompass the pictures that need to be added, that i just added to /static/images/timeline

**Comment by ClareCat21** [comment]
Thanks! I finished my first one in backg_1_dowling.txt - could you check it to make sure I did it right? Don't want to do all of them and realize I'm messing up lol

**Comment by defjosiah** [comment]
Hey, I'm checking it out... It isn't working at the moment, but I'm figuring out why

**Comment by defjosiah** [comment]
@ClareCat21 hey, I just pushed a working version, it looks like the default for the computer is "/" as a directory for background, which means that all you have to do it "/static/images/timeling/xxx.jpg" 

also on the images from websites make sure to include the actual image, so in the one you had you had http://exhibits.library.rice.edu/items/show/514, which is the main page view, when you need this, http://exhibits.library.rice.edu/files/original/51a7c6e6a99f395022d7d1bcd08515ca.jpg, which is the file you were referring to

**Comment by ClareCat21** [comment]
ok i'll check those - i think that's the only one i screwed up but i'll make sure when i'm going through later
